config/routes.rb
Rails.application.routes.draw do
  root to: 'home#top'
  devise_for :users
  resources :books
  resources :users, only: [:show, :index, :edit, :update]
  get 'home/about' => 'home#about'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
 belongs_to :user
 
 validates :title, presence: true

 validates :body, presence: true
 validates :body, length: { maximum: 200 }
# validates :body, length: {  in: 1..200 }

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length: { in: 2..20 }

  validates :introduction, length: { maximum: 50 }

#プロフィール画像用 deviseに入ってるかも
  attachment :profile_image


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected
  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  private
  # def configure_permitted_parameters
  #     devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  # end
  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_book,only: [:edit,:update]
  
  def index
    @books = Book.all
    @user = current_user
    # @user_data = current_user
    @book = Book.new
  end

  def show
     @book = Book.find(params[:id])
    # @bookのユーザー
     @user = @book.user
     @book_new = Book.new
  end

  # def new
  #   @book = Book.new
  #   redirect_to book_path(@book.id)
  # end
  
  def create
     # １. データを新規登録するためのインスタンス作成
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    # binding.pry
     # ２. データをデータベースに保存するためのsaveメソッド実行
    if @book.save
      flash[:notice] = "Book was successfully created."
       # ３. ブック詳細画面へリダイレクト
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def edit
     @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :edit
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = "Book was successfully destroyed."
    redirect_to books_path
  end
  
   def correct_book
        @book = Book.find(params[:id])
    unless @book.user.id == current_user.id
      redirect_to books_path
    end
   end
  
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    # 使う
    # new
    # create
    # index
    # edit
    # update
    
    
    
  def index
    @users = User.all
    @user = User.new
  end

  def show
     @user = User.find(params[:id])
  end

  # def new
  #   @book = Book.new
  # end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome! You have signed up successfully."
      # ユーザー詳細ページに飛ばす
      redirect_to user_path(@user.id)
    else
      @users = User.all
      # サインアップの入力ページ
      render 'index'
    end
  end

  def edit
     @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      # ユーザー詳細ページに飛ばす
      redirect_to user_path(@user.id)
    else
      @users = User.all
      # ユーザー編集ページに飛ばす
      render 'edit'
    end
  end
  
  def destroy
    user = User.find(params[:id])
    user.destroy
    flash[:notice] = "Book was successfully destroyed."
    redirect_to users_path
  end
  
  
  private
  def user_params
    params.require(:user).permit(:name, :profile_image_id,:introduction)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user,only: [:edit,:update]
  
  def index
    @users = User.all
    @user = current_user
    @books = Book.all
    @book = Book.new
  end

  def show
     @user = User.find(params[:id])
     @book = Book.new
     @books = @user.books
  end

  # def new
  #   @book = Book.new
  # end
  
  # def create
  #   @user = User.new(user_params)
  #   if @user.save
  #     flash[:notice] = "Welcome! You have signed up successfully."
  #     # ユーザー詳細ページに飛ばす
  #     redirect_to user_path(@user.id)
  #   else
  #     @users = User.all
  #     # サインアップの入力ページ
  #     render 'index'
  #   end
  # end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user = current_user
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      # ユーザー詳細ページに飛ばす
      redirect_to user_path(@user.id)
    else
      @users = User.all
      # ユーザー編集ページに飛ばす
      render :edit
    end
  end
  
  # def destroy
  #   user = User.find(params[:id])
  #   user.destroy
  #   flash[:notice] = "Book was successfully destroyed."
  #   redirect_to users_path
  # end
  
  
  def correct_user
        @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end
  
  
  private
  def user_params
    params.require(:user).permit(:name, :profile_image,:introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/books/_info.html.erb
<!--ユーザーインフォを入れる　ここから-->
<p>
  <h2>User info</h2>
    <%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg"%>
</p>
<table class="table">
 <tbody>
  <tr>
    <th>Name</th>
    <th><%= user.name %></th>
  </tr>
  <tr>
    <th>Introduction</th>
    <th><%= user.introduction %></th>
  </tr>
 </tbody>
</table>
<!--ユーザーインフォを入れる　ここまで-->
 
<!--編集用ボタン-->
<div class="row">
<%# if user.id == current_user.id %>
 <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
  <i class="fas fa-user-cog"></i>
 <%# end %>

 <% end %>
</div>

app/views/books/_message.html.erb
<!--成功時のメッセージ-->
<% if flash[:notice] %>
<div class="text-success">
  <p id="notice">
    <%= flash[:notice] %>
  </p>
</div>
<% end %>

<!--エラー時のメッセージ-->
<% if book.errors.any? %>
    <div id="error_explanation",class="text-danger">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this obj from being saved:</h2>
      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/books/_new.html.erb
<h1>New book</h1>
<!-- form_with部分 -->
<%= form_with model:book, local:true do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>
  
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book', class:"btn btn-success" %>
<% end %>

app/views/books/edit.html.erb
<!--ブック編集ページ-->
<h1>Editing Book</h1>
  <!--成功時・エラー時メッセージ-->
  <%= render 'books/message', book: @book %>
  
 <!--form_withを利用すると、インスタンス変数を渡すだけで、インスタンス変数内のモデルを解読して、投稿したタイトルと内容を代入してくれる-->
 <%= form_with model: @book, url: book_path, local: true do |f| %>
 <p>
   <div>Title</div>
   
    <%= f.text_field :title, class:"mb-1" %>
 </p>
 <p>
   <div>Body</div>
    <%= f.text_field :body, class:"mb-1" %>
 </p>
 <div class="actions">
     <!--<input type="submit" name="commit" value="Update Book" data-disable-with="Update Book">-->
     <%#= link_to "Update Book",book_path(@book.id), class:"btn btn-success mb-1" %>
      <%= f.submit "Update Book", class:"btn btn-success mb-1" %>
 </div>
 <% end %>
 
 <%= link_to "Show",book_path(@book.id) %>
  |
 <%= link_to "Back",books_path %>

app/views/books/index.html.erb
<!--ブック一覧-->
<div>
 <!--成功時・エラー時メッセージ-->
  <%= render 'books/message', book: @book %>

  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3"> 
      
        <!--ユーザーインフォ-->
        <%= render 'books/info', user: @user %>
        
        <!--New book-->
        <%= render 'books/new', book: @book %>
    
      </div>
      <div class="col-md-8 offset-md-1"> 
        <h2>Books</h2>
        <!--Title用-->
          <table class="table table-hover able-inverse">
            <thead>
              <tr>
                <th scope="col"></th>
                <th scope="col">Title</th>
                <th scope="col">Body</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <% @books.each do |book| %>
            <tbody>
              <tr>
                <th scope="row">
                  <!--ユーザーページに飛ばす-->
                  <%= link_to user_path(book.user) do %>
                    <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size: "40x40" %>
                  <% end %>
                </th>
                <!--本の詳細画面に飛ばす-->
                <td><%= link_to book.title,book_path(book.id) %></td>
                <td><%= book.body %></td>
                <td></td>
              </tr>
              </tbody>
            <% end %>
          </table>
                <!--<td><%#= link_to "Show",show_path(@book.id) %></td>-->
                <!--<td><%#= link_to "Edit",edit_path(@book.id) %></td>-->
                <!--<td><%#= link_to destroy_path(@book), "Destroy", method: :delete, data: {confirm: "Are you sure?"}%></td>-->
       </div>
      
      </div>
      </div>
  </div>

app/views/books/show.html.erb
<!--本の詳細ページ-->
<div class="container px-5 px-sm-0">
  <div class="row">
 
   <body>
    <div class="col-md-3"> 
     
       <!--成功時・エラー時メッセージ-->
        <%= render 'books/message', book: @book %>
       
       <!--ユーザーインフォ-->
       <%= render 'books/info', user: @user %>
       
       <!--New book-->
       <%= render 'books/new', book: @book_new %>
   
    </div>
 
    <div class="col-md-8 offset-md-1"> 
     <!--Book detailの部分　ここから--> 
    <h2>Book detail</h2>
      <table class="table">
      <thead></thead>
       <tbody>
        <tr>
          <th scope="col">
           <!--ユーザーページに飛ばす画像と名前のところ両方とも-->
           <p>
            <%= link_to user_path(@user.id) do %>
             <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size: "40x40" %>
            <% end %>
           </p>
           <!--ユーザーページに飛ばす画像と名前のところ両方とも-->
           <p><%= link_to @user.name,user_path(@user.id) %></p>
          </th>
          <!--本の詳細画面に飛ばす-->
          <th scope="col"><%= link_to @book.title,book_path(@book.id)%></th>
          <th scope="col"><%= @book.body %></th>
          
           <% if @user.id == current_user.id %>
           <th scope="col"><%= link_to "Edit",edit_book_path(@book.id), class:"btn btn-sm btn-success" %></th>
           <th scope="col"><%= link_to "Destroy", book_path(@book.id), method: :delete, class:"btn btn-sm btn-danger" %></th>
           <th></th>
           <% end %>
        </tr>
       </tbody>
      </table> 
    <!--Book detailの部分　ここまで-->
    </div>
 
  </body>
 
 </div>
</div>

app/views/home/about.html.erb
<main>
  <p id="notice"></p>
    <div class="container">
      <div class="row">
        <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
      </div>
    </div>
</main>
    

app/views/home/top.html.erb
<main>
  <!--<p id="notice"></p>-->
  <!--成功時のメッセージ　ここから-->
  <% if flash[:notice] %>
    <div class="text-success">
      <p id="notice">
        <%= flash[:notice] %>
      </p>
    </div>
  <% end %>
  <!--成功時のメッセージ　ここまで-->
  <div class="container">
    <div class="row">
      <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
        <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
        <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <!--<a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>-->
            <%= link_to "Log in", "/users/sign_in", class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
          </div>
          <div class="row">
            <!--<a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>-->
            <%= link_to "Sign Up", "/users/sign_up", class: "btn btn-success btn-sm btn-block sign_up" %>
          </div>
        </div>
        
      </div>
    </div>
  </div>

</main>

app/views/layouts/application.html.erb
  <!DOCTYPE html>
  
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/*******.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
  </head>
  <body>
    <% if user_signed_in? %>
      <!--headerここから-->
     <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <!--<div class="row">-->
          <!--<a class="navbar-brand" href="/"><span>Bookers</span></a>-->
          <%= link_to "Bookers", "/", class: "navbar-brand" %>
          <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="navbar-collapse collapse" id="navbarNavDropdown" style="">
            <ul class="navbar-nav ml-auto">
              <li><%= link_to 'Home', user_path(current_user.id), class:"fas fa-home nav-link text-light"%></li>
              <!--<li><a class="fas fa-users nav-link text-light" href="/users"> Users</a></li>-->
              <li><%= link_to " Users", "/users", class: "fas fa-users nav-link text-light" %></li>
              <!--<li><a class="fas fa-book-open nav-link text-light" href="/books"> Books</a></li>-->
              <li><%= link_to " Books", "/books", class: "fas fa-book-open nav-link text-light" %></li>
              <!--<li><a class="fas fa-sign-out-alt nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out"> logout</a></li>-->
              <li><%= link_to " logout", "/users/sign_out", class: "fas fa-sign-out-alt nav-link text-light", method: :delete %></li>
            </ul>
          </div>
        <!--</div>    -->
       </div>
      </nav>
    </header>
    <!--headerここまで-->


    <% else %>
      <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <div class="container">
            <!--<a class="navbar-brand" href="/"><span>Bookers</span></a>-->
            <%= link_to "Bookers", "/", class: "navbar-brand" %>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                <!--<li><a class="fas fa-home nav-link text-light" href="/"> Home</a></li>-->
                <li><%= link_to 'Home', "/", class:"fas fa-home nav-link text-light"%></li>
                <!--<li><a class="fas fa-link nav-link text-light" href="/home/about"> About</a></li>-->
                <li><%= link_to " About", "/home/about", class: "fas fa-link nav-link text-light" %></li>
                <!--<li><a class="fas fa-user-plus nav-link text-light" href="/users/sign_up"> sign up</a></li>-->
                <li><%= link_to " sign up", "/users/sign_up", class: "fas fa-user-plus nav-link text-light" %></li>
                <!--<li><a class="fas fa-sign-in-alt nav-link text-light" href="/users/sign_in"> login</a></li>-->
                <li><%= link_to " login", "/users/sign_in", class: "fas fa-sign-in-alt nav-link text-light" %></li>
              </ul>
            </div>
          </div>
        </nav>
      </header>
      
    <% end %> 
    
    <div class="container-fluid ">
    <div class="row">
    <div class="col-sm-12 col-md-8 px-5 px-sm-0 mx-auto">  
      <main> 
          
          <%= yield %>
          
      </main>
    </div>
    </div>
    </div>
    
    <!--footerここから-->
    <footer>
      <div class="container mt-5">
      	<div class="row">
        	<div class="mx-auto">
        		<p>CopyRight Infratop.inc</p>
        	</div>
        </div>
      </div>
    </footer>

<!--footerここまで-->
  </body>
</html>

app/views/user/edit.html.erb
<!--<head>-->
<!--    <title>Bookers2Ver2</title>-->
<!--    <meta name="csrf-param" content="authenticity_token">-->
<!--<meta name="csrf-token" content="lLZEkmd2ZqneqK5KOjmPkJtGunRqv1SsFhl7mK8vEWeG8DGOdFr6EgIbiAnLiNhIuqKsoguvIU+u/ibWseb1Kw==">-->
    
<!--    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">-->
<!--    <link rel="stylesheet" media="all" href="/assets/application-16605eadccf37c23d1fa922dd614f45b9f2cf25723e2e4032f1975b02ea7d11f.css" data-turbolinks-track="reload">-->
<!--    <script src="/assets/application-3ac47b8571e58aab844e8d0a988f0f55d8a16c1a75953470343f79cf1bec8528.js" data-turbolinks-track="reload"></script>-->
<!--  </head>-->
  
<!--  <body>-->
<!--    <header>-->
<!--  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">-->
<!--    <div class="container">-->
<!--      <a class="navbar-brand" href="/"><span>Bookers</span></a>-->
<!--      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">-->
<!--        <span class="navbar-toggler-icon"></span>-->
<!--      </button>-->
<!--      <div class="collapse navbar-collapse" id="navbarNavDropdown">-->
<!--        <ul class="navbar-nav ml-auto">-->
<!--          <li><a class="fas fa-home nav-link text-light" href="/users/5555"> Home</a></li>-->
<!--          <li><a class="fas fa-users nav-link text-light" href="/users"> Users</a></li>-->
<!--          <li><a class="fas fa-book-open nav-link text-light" href="/books"> Books</a></li>-->
<!--          <li><a class="fas fa-sign-out-alt nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out"> logout</a></li>-->
<!--        </ul>-->
<!--      </div>-->
<!--    </div>-->
<!--  </nav>-->
<!--</header>-->
<!--      <main>-->
<!--        <p id="notice"></p>-->
<!--        <div class="container">-->
<!--  <div class="row">-->
<!--    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">-->
<!--    <h2>User info</h2>-->
<!--    <form enctype="multipart/form-data" action="/users/5555" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="_method" value="patch"><input type="hidden" name="authenticity_token" value="lLZEkmd2ZqneqK5KOjmPkJtGunRqv1SsFhl7mK8vEWeG8DGOdFr6EgIbiAnLiNhIuqKsoguvIU+u/ibWseb1Kw==">-->
<!--        <div id="error_explanation">-->
<!--    <h3>1 error prohibited this obj from being saved:</h3>-->
<!--    <ul>-->
<!--        <li>Name is too short (minimum is 2 characters)</li>-->
<!--    </ul>-->
<!--  </div>-->

<!--      <div class="form-group">-->
<!--        <div class="field_with_errors"><label for="user_name">Name</label></div>-->
<!--        <div class="field_with_errors"><input class="form-control name" type="text" value="" name="user[name]" id="user_name"></div>-->
<!--      </div>-->
<!--     <div class="form-group">-->
<!--        <label for="user_image">Image</label>-->
<!--        <input value="{}" data-reference="e108ca0b82ae8fd5b6bb51894c55c156" type="hidden" name="user[profile_image]"><input class="form-control-file user_image" data-reference="e108ca0b82ae8fd5b6bb51894c55c156" include_hidden="false" type="file" name="user[profile_image]" id="user_profile_image">-->
<!--      </div>-->
<!--      <div class="form-group">-->
<!--        <label for="user_introduction">Introduction</label>-->
<!--        <textarea class="form-control introduction" name="user[introduction]" id="user_introduction">aaa</textarea>-->
<!--      </div>-->
<!--      <div class="form-group">-->
<!--        <input type="submit" name="commit" value="Update User" class="btn btn-secondary" data-disable-with="Update User">-->
<!--      </div>-->
<!--</form>  </div>-->
<!--</div>-->

<!--      </div></main>-->
<!--    <footer>-->
<!--  <div class="container mt-5">-->
<!--  	<div class="row">-->
<!--    	<div class="mx-auto">-->
<!--    		<p>CopyRight Infratop.inc</p>-->
<!--    	</div>-->
<!--    </div>-->
<!--  </div>-->
<!--</footer>-->

  

<!--</body>-->




<body>
     <!--エラー時のメッセージ-->
  <% if @book.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
  <% end %>
  
 <p>
   <!--<strong>Name</strong>-->
   <!--<p><%= @user.name %></p>-->
   <!--<div class="field_with_errors"><input class="form-control name" type="text" value="" name="user[name]" id="user_name"></div>-->
   <h2>User info</h2>
   <%= form_with model:@user, local:true do |f| %>
   <strong><label for="inputName">Name</label></strong>
   <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
 </p>
 
 <p>
   <!--<strong>Image</strong>-->
   <!--<p><%= @user.profile_image_id %></p>-->
   <!--<textarea class="form-control introduction" name="user[introduction]" id="user_introduction">aaa</textarea>-->
   
   <!--画像選択する-->
   <!--<input value="{}" data-reference="e108ca0b82ae8fd5b6bb51894c55c156" type="hidden" name="user[profile_image]"><input class="form-control-file user_image" data-reference="e108ca0b82ae8fd5b6bb51894c55c156" include_hidden="false" type="file" name="user[profile_image]" id="user_profile_image">-->
   <%= attachment_image_tag @user, :profile_image_id, :fill, 60, 60, fallback: "no_image.jpg"%>
    <strong><label for="inputImage">Image</label></strong>
   <%= f.attachment_field :profile_image_id, placeholder: "プロフィール画像" %>

 </p>

 <p>
   <strong>Introduction</strong>
   <p><%= @user.introduction %></p>
   <!--<textarea class="form-control introduction" name="user[introduction]" id="user_introduction"></textarea>-->
 </p>
 
 
<!--<div class="form-group">-->
<!--    <input type="submit" name="commit" value="Update User" class="btn btn-secondary" data-disable-with="Update User">-->
<!--</div>-->

 <%= f.submit "Update User" %>
 <% end %>

app/views/users/edit.html.erb
<!--ユーザー編集ページ-->
<p>
 <h2>User info</h2>
 <%= form_with model:@user, local:true do |f| %>
 
   <!--エラー時のメッセージ-->
 <% if @user.errors.any? %>
     <div id="error_explanation">
         <h2><%= @user.errors.count %> prohibited this obj from being saved:</h2>
         <ul>
             <% @user.errors.full_messages.each do |message| %>
                 <li><%= message %></li>
             <% end %>
         </ul>
     </div>
 <% end %>

  <label for="inputName">Name</label></br>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前", class:"mb-1"%>

  <p>
     <%#= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
     <label for="inputImage">Image</label>
     <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class:"form-control-file mb-1"%>
  </p>
   
  <p>Introduction</br>
     <%#= @user.introduction %>
     <%= f.text_field :introduction, class:"mb-1" %><%#= @user.introduction%>
     <%#= f.attachment_field :introduction, text:@user.introduction %>
  </p>

  <%= f.submit "Update User", class:"btn btn-secondary" %>
 <% end %>
</p>

app/views/users/index.html.erb
<!--ユーザー一覧-->
<div class="container px-5 px-sm-0">
　<div class="row">
 
   <div class="col-md-3"> 
      <!--ユーザーインフォ-->
      <%= render 'books/info', user: @user %>
      <!--New book-->
      <%= render 'books/new', book: @book %>
   </div>  
 
   <div class="col-md-8 offset-md-1">
   <!--Usersの部分　ここから-->
   <h2>Users</h2>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">image</th>
          <th scope="col">name</th>
          <th colspan="3"></th>
          <th></th>
        </tr>
      </thead>
      
      <% @users.each do |user| %>
        <tbody>
            <thead>
              <tr>
                <th scope="col"><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "40x40" %></th>
                <td><%= user.name %></td>
                <td colspan="3"></td>
                <td><%= link_to "Show",user_path(user.id) %></td>
                <td></td>
              </tr>
            </thead>
        </tbody>
      <% end %>
    </table>
   </div>
  
  </div>
</div>